### ISSUE TITLE
Issue with scipy shift function in DataLoader.py

### ISSUE THREAD

**Issue by yunseok624** [Suanmd/TR-MISR#9]
Hi,
Followed the exact instruction and encountered with such a problem with **scipy.ndimage shift** function:
s = phase_cross_correlation(reference_image=lr_images[0],
  0%|                                                                 | 0/835 [00:04<?, ?it/s]
  0%|                                                                 | 0/400 [00:04<?, ?it/s] 
Traceback (most recent call last):
  File "C:\Users\Юнсок\Desktop\Research\MISR_research\TR-MISR-master\src\train.py", line 302, in <module>
    main(config)
  File "C:\Users\Юнсок\Desktop\Research\MISR_research\TR-MISR-master\src\train.py", line 289, in main
    trainAndGetBestModel(fusion_model, optimizer, dataloaders, baseline_cpsnrs, config)        
  File "C:\Users\Юнсок\Desktop\Research\MISR_research\TR-MISR-master\src\train.py", line 75, in trainAndGetBestModel
    for lrs, lr_maps, alphas, hrs, hr_maps, names in tqdm(dataloaders['train']):
  File "C:\Users\Юнсок\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\std.py", 
line 1178, in iter
    for obj in iterable:
  File "C:\Users\Юнсок\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 630, in next
    data = self._next_data()
  File "C:\Users\Юнсок\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "C:\Users\Юнсок\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "C:\Users\Юнсок\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Юнсок\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Юнсок\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Юнсок\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Юнсок\Desktop\Research\MISR_research\TR-MISR-master\src\DataLoader.py", line 166, in getitem
    imset = [read_imageset(imset_dir=dir_,
  File "C:\Users\Юнсок\Desktop\Research\MISR_research\TR-MISR-master\src\DataLoader.py", line 166, in <listcomp>
    imset = [read_imageset(imset_dir=dir_,
  File "C:\Users\Юнсок\Desktop\Research\MISR_research\TR-MISR-master\src\DataLoader.py", line 89, in read_imageset
    lr_images[i] = shift(lr_images[i], s,  mode='constant', cval=0)
  File "C:\Users\Юнсок\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\ndimage\_interpolation.py", line 684, in shift
    shift = _ni_support._normalize_sequence(shift, input.ndim)
  File "C:\Users\Юнсок\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\ndimage\_ni_support.py", line 67, in _normalize_sequence
    raise RuntimeError(err)
RuntimeError: sequence argument must have length equal to input rank

I do I encounter such problem? Anyone solved this kind of problem?

**Comment by ser5kovskiy** [comment]
As I undrstad, the issue is that with newer versions return format changed. I am donig:
```
for i in range(1, lr_images.shape[0]):
        s = phase_cross_correlation(reference_image=lr_images[0],
                                    moving_image=lr_images[i], 
                                    return_error=False, 
                                    reference_mask=lr_maps[0], 
                                    moving_mask=lr_maps[i],
                                    overlap_ratio=0.99)
        #NEW LINE
        s = s[0]
        lr_images[i] = shift(lr_images[i], s,  mode='constant', cval=0)
        lr_maps[i] = shift(lr_maps[i], s, mode='constant', cval=0)
```

**Comment by yunseok624** [comment]
It worked, thanks
